---
title: "misc_remove_later"
author: "Adnan M. Niazi"
date: "5/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4. Nanopolish's tail end estimate vs. tail end estimate obtained by alignment of eGFP
Lets estimate if the coordinates of the tail end estimated by Nanopolish match up with those obtained from the alignment with eGFP sequence.
```{r, warning=FALSE}
p <- ggplot(rna_kr_data, aes(x = tail_end_np, y = transcript_alignment_start)) +
    geom_point(shape = 21, colour = 'black', fill = 'black', size = 2, stroke=0, alpha = 0.1) +
    geom_abline(intercept = 0, slope = 1, color="red", linetype = 'dotted', size = 0.7) +
    geom_smooth(method = 'lm',formula = y~x, color="#797979", fullrange = TRUE, se = FALSE, size = 0.5) +
    stat_cor(method = "pearson", label.x = 5000, label.y = 30000) +
    coord_cartesian(xlim = c(0, 40000), ylim = c(0, 40000))
```

```{r, warning=FALSE, echo=FALSE}
p <- p + theme_bw() +
  theme(
    axis.line =element_line(colour = "black"),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank()
  ) +
  xlab('Nanopolish tail end') +
  ylab('tail end estimated with eGFP alignment')
p
```


Now we present the same information as histogram.
```{r, warning=FALSE}
data <- mutate(rna_kr_data, diff = tail_end_np - transcript_alignment_start)
p <- ggplot(data, aes(x = diff)) + 
  geom_histogram(binwidth = 1) + 
  theme_bw() + 
  coord_cartesian(xlim = c(-1000, 1000)) +
  scale_x_continuous(minor_breaks = seq(-1000, 1000, 50)) +
  xlab('Nanopolish tail end - tail end estimated with eGFP alignment') 
p
```


## 6. Nanpolish vs. tailfindr vs. eGFP end
```{r}
rna_kr_data_np_tf_gfp_all_present <- rna_kr_data %>% 
  filter(!is.na(tail_end_tf) & !is.na(tail_end_np) & !is.na(transcript_alignment_start))

rna_kr_data_np_tf_gfp_all_present %<>% 
  mutate(df_np_gfp = tail_end_np - transcript_alignment_start) %>% 
  mutate(df_tf_gfp = tail_end_tf - transcript_alignment_start)  %>% 
  select(df_np_gfp, df_tf_gfp) %>% 
  gather(key = "condition", value = "diff",)
  
  p <- ggplot(rna_kr_data_np_tf_gfp_all_present, aes(x = diff, color = condition, fill = condition)) +
  geom_freqpoly(binwidth = 1) +
  coord_cartesian(xlim = c(-1000, 1000)) 
  #scale_x_continuous(minor_breaks = seq(-200, 200, 50)) 
p
```